### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'blkid'

### ISSUE THREAD

**Issue by GrahamCobb** [Ferroin/btrfs-subv-backup#2]
I am not too worried about this but I think your README says that the script is intended to work without blkid available:

Traceback (most recent call last):
  File "./btrfs-subv-backup.py", line 357, in <module>
    sys.exit(main())
  File "./btrfs-subv-backup.py", line 333, in main
    fsinfo = get_fs_info(args.path, verbose=args.verbose)
  File "./btrfs-subv-backup.py", line 146, in get_fs_info
    ret['uuid'] = subprocess.check_output(['blkid', '-o', 'value', '-s', 'UUID', ret['device']]).decode().rstrip()
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'blkid'

It turns out that, in this case, I was not running as root and so blkid was not in my path, although it is installed on the system. Obviously the script is not going to work when not run as root so you might decide to just close this issue altogether.

**Comment by Ferroin** [comment]
I had not tested it as a non-root user (otherwise I would have caught this, my systems don't have `/sbin` in the path for non-root users), but the saving process _should_ work as a non-root user (the info in the README about using `btrfs subvolume list` is actually old, I had forgotten that I had changed the script to not use that before I even made the first commit), and so should a restore, although restoring as a non-root user will probably give incorrect subvolume ownership.

All that aside, fixed now on master.
